name: flask-helloworld
on:
    push:
        branches: [master]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps: # Add two spaces here
            - name: Checkout
              uses: actions/checkout@v2
